### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by hapm** [murank/redmine_kramdown_formatter#3]
The plugin fails on redmine 4.0.5 with rails 5.2.3 because `alias_method_chain` got removed in rails 5.

```
rake aborted!
NoMethodError: undefined method `alias_method_chain' for Kramdown::Converter::Html:Class
Did you mean?  alias_method
/usr/src/redmine/plugins/redmine_kramdown_formatter/lib/kramdown/converter/html_patch.rb:29:in `block in included'
/usr/src/redmine/plugins/redmine_kramdown_formatter/lib/kramdown/converter/html_patch.rb:28:in `class_eval'
/usr/src/redmine/plugins/redmine_kramdown_formatter/lib/kramdown/converter/html_patch.rb:28:in `included'
/usr/src/redmine/plugins/redmine_kramdown_formatter/lib/kramdown/converter/html_patch.rb:65:in `include'
/usr/src/redmine/plugins/redmine_kramdown_formatter/lib/kramdown/converter/html_patch.rb:65:in `<module:Converter>'
/usr/src/redmine/plugins/redmine_kramdown_formatter/lib/kramdown/converter/html_patch.rb:22:in `<module:Kramdown>'
/usr/src/redmine/plugins/redmine_kramdown_formatter/lib/kramdown/converter/html_patch.rb:21:in `<top (required)>'

/usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `each'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/usr/src/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/bundle/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

**Comment by jdimeo** [comment]
@hapm I was able to get past this error with the following patch:
```
--- a/plugins/redmine_kramdown_formatter/lib/kramdown/converter/html_patch.rb
+++ b/plugins/redmine_kramdown_formatter/lib/kramdown/converter/html_patch.rb
@@ -26,9 +26,12 @@ module Kramdown
         base.send(:include, InstanceMethods)
 
         base.class_eval do
-          alias_method_chain :convert_a, :redmine
-          alias_method_chain :convert_codeblock, :redmine
-          alias_method_chain :convert_codespan, :redmine
+          alias_method :convert_a_without_redmine, :convert_a
+          alias_method :convert_a, :convert_a_with_redmine
+          alias_method :convert_codeblock_without_redmine, :convert_codeblock
+          alias_method :convert_codeblock, :convert_codeblock_with_redmine
+          alias_method :convert_codespan_without_redmine, :convert_codespan
+          alias_method :convert_codespan, :convert_codespan_with_redmine
         end
       end
```
Will open a PR when I get the chance
